### ISSUE TITLE
ctrl+c on password prompt causes all future login attempts to fail

### ISSUE THREAD

**Issue by minapoli** [TresysTechnology/clip#156] opened 2015-05-19 17:20 UTC
I came across this on a debug install:
1) log in as toor
2) `sudo ls -l /` (or any sudo command)
3) ctrl+c at password prompt

All future sudo attempts fail for invalid password.  Logging out and attempting to log back in again will also fail for an invalid password.  The problem only occurs when running a sudo command (hitting ctrl+c during the password prompt at login doesn't cause it)
Rebooting the system fixes the problem.

**Comment by ykhodorkovskiy** [comment] 2015-05-19 20:17
We should investigate if this is a CLIP problem or a RHEL 7 problem (verify pam rpm versions are identical)

**Comment by ykhodorkovskiy** [comment] 2015-05-19 20:43
ctrl+c works in a RHEL 7 VM and the pam versions are identical to CLIP.

**Comment by ykhodorkovskiy** [comment] 2015-05-19 21:01
@minapoli This is caused by our SSG pam remediation. I am not sure which module is causing this and if it is a bug in PAM or intended behavior. Marking this as a lower priority for now.

**Comment by ykhodorkovskiy** [comment] 2015-10-06 15:20
We can take a look at this for the final release if we have time, otherwise document

**Comment by ykhodorkovskiy** [comment] 2015-12-04 16:31
@minapoli @pebenito I think this is probably worth just documenting as a known issue

**Comment by pebenito** [comment] 2015-12-07 14:12
I suggest marking as known issue and then revisit in the next release.

**Comment by ykhodorkovskiy** [comment] 2015-12-07 16:01
@minapoli document as a known issue in README.md and mention it in the final release email.

**Comment by rprevette** [comment] 2016-03-01 20:58
This does not seem to be reproducible in the 7.2 milestone currently.

Tested in Debug mode, in Permissive.

**Closed** 2016-03-03 18:03 UTC
Labels: bug, Low Priority, medium-task
